apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  # High-volume and low-risk so drop them.
  - level: None
    users: ["system:kube-proxy"]
    verbs: ["watch"]

  - level: None
    users: ["system:unsecured"]
    namespaces:
      - kube-system
    resources:
      - group: "" # core
        resources: ["endpoints"]

  - level: None
    # Ingress controller probes health checks
    users:
      - system:serviceaccount:kube-system:traefik   # default Helm/chart SA name
    verbs: ["get", "list", "watch"]
    resources:
      - group: "" # core group
        resources: ["services", "endpoints", "endpointslices", "pods", "nodes"]
      - group: "discovery.k8s.io"
        resources: ["endpointslices"]
      - group: "networking.k8s.io"
        resources: ["ingresses"]
      - group: "traefik.io" # if using Traefik CRDs like IngressRoute, Middleware, etc.
        resources: ["ingressroutes", "middlewares", "ingressroutetcps", "ingressrouteudps", "tlsoptions", "tlsstores"]
      - group: "apiextensions.k8s.io"
        resources: ["customresourcedefinitions"]  # Traefik often lists CRDs

  - level: None
  # Don't log these read-only requests
    resources:
      - group: ""
        resources: ["namespaces", "nodes"]
    verbs: ["get", "list", "watch"]

  # Default: log at Metadata level all other requests.
  - level: Metadata
    omitStages:
      - RequestReceived