#!/usr/bin/env bash
setlocal

# Script to install and configure MetalLB Load Balancer for Kubernetes
# Written by Dustin Pollreis

# Variables
set "MetalLB_VER=%~1"

# Check for parameter
if "%~1"=="" (
    echo Error: No MetalLB version provided.
    echo Usage: install-metallb.sh [MetalLB_Version]
    exit /b 1
)


# Install MetalLB (Layer 2 Mode)
kubectl apply -f \
"https://raw.githubusercontent.com/metallb/metallb/$MetalLB_VER/config/manifests/metallb-native.yaml"

# Verify
kubectl get pods -n metallb-system

# Apply metallb config
kubectl apply -f ~/.kube/metallb.yaml

# Verify MetalLB is working
# Check MetalLB pods
kubectl get pods -n metallb-system

# Confirm the IP pool
kubectl get ipaddresspools -n metallb-system

endlocal